# Generated by Django 4.2.5 on 2023-12-07 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculty',
            old_name='user',
            new_name='faculty',
        ),
    ]
